gifts/urls.py
from django.urls import path

from .views import (
    gifts_list_create_view,
    gifts_list_detail_view,

    gift_create_view,
    gift_detail_view,
    gift_update_view,
    gift_delete_view,
)

urlpatterns = [
    path('gifts_list_create', gifts_list_create_view, name='gifts_list_create_view'),
    path('gifts_list/<int:pk>', gifts_list_detail_view, name='gifts_list_detail_view'),

    path('gifts_list/<int:gifts_list_pk>/gift_create', gift_create_view, name='gift_create_view'),

    path('gift/<int:gift_pk>/detail', gift_detail_view, name='gift_detail_view'),
    path('gift/<int:gift_pk>/update', gift_update_view, name='gift_update_view'),
    path('gift/<int:gift_pk>/delete', gift_delete_view, name='gift_delete_view'),
]

simple_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users.views import register_user_view
from pages.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', landing_page, name='landing_page'),
    path('gifts/', include('gifts.urls')),
    path('user/', include('users.urls')),
    
    path('register/', register_user_view, name='register'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
]

users/urls.py
from django.urls import path

from .views import (
    home_page_view
)

urlpatterns = [
    path('home_page', home_page_view, name='user_home_page_view'),
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users.views import register_user_view
from pages.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', landing_page, name='landing_page'),
    path('gifts/', include('gifts.urls')),
    path('user/', include('users.urls')),
    
    path('register/', register_user_view, name='register'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
]

gifts/models.py
from slugify import slugify

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import Http404

# Create your models here.
class GiftsList(models.Model):
    name = models.CharField(max_length=200, default='')
    slug = models.SlugField(default='')
    password = models.CharField(max_length=200, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('gifts_list_detail_view', kwargs={"pk": str(self.pk)})

    def can_user_edit(self, user):
        if user.id != self.owner.pk:
            raise Http404("You are not allowed to edit gifts list!")
        return True

    @staticmethod
    def create_default_gifts_list(user):
        default_gifts_list_name = 'moja lista prezentów'
        gifts_list = GiftsList(
            name=f'{user.username} - {default_gifts_list_name}',
            slug=slugify(' '.join((user.username, default_gifts_list_name))),
            password=None,
            owner=user
        )
        gifts_list.save()
    

class Gift(models.Model):
    name = models.CharField(max_length=200)
    status = models.CharField(max_length=200, blank=True, null=True)
    img_url = models.CharField(max_length=400, blank=True, null=True)
    gifts_list = models.ForeignKey(GiftsList, on_delete=models.CASCADE)

    def can_user_edit(self, user):
        if user.id != self.gifts_list.owner.pk:
            raise Http404("You are not allowed to edit gifts list!")
        return True

class GiftUrl(models.Model):
    url = models.CharField(max_length=400)
    gift = models.ForeignKey(Gift, on_delete=models.CASCADE)

pages/models.py
from django.db import models

# Create your models here.

gifts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from crispy_forms.layout import Submit

from .models import GiftsList, Gift


class GiftsListForm(forms.ModelForm):

	class Meta:
		model = GiftsList
		fields = ['name', 'password']
		labels = {
			'name': ('Nazwa twojej listy:'),
			'password': ('Hasło'),
        }

class GiftForm(forms.ModelForm):

	class Meta:
		model = Gift
		fields = ['name']
		labels = {'name': ('Nazwa')}

gifts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import GiftsList, Gift
from .forms import GiftsListForm, GiftForm

# GIFTS_LIST:
@login_required
def gifts_list_create_view(request):
	if request.method == 'POST':
		form = GiftsListForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.owner = request.user
			obj = form.save()
			return redirect(gifts_list_detail_view, pk=obj.pk)
	else:
		form = GiftsListForm()
	
	template = 'gifts/gift_form.html'
	context = {
		'form': form,
	}
	return render(request, template, context)

def gifts_list_detail_view(request, pk):
	obj = obj = get_object_or_404(GiftsList, pk=pk)
	template = 'gifts/gifts_list_detail_view.html'
	context = {
		'object': obj
	}
	return render(request, template, context)


# GIFTS:
#---------------------------------------------------------------------------------------------
@login_required
def gift_create_view(request, gifts_list_pk):

	gifts_list = get_object_or_404(GiftsList, pk=gifts_list_pk)
	gifts_list.can_user_edit(request.user)

	if request.method == 'POST':
		form = GiftForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.gifts_list = gifts_list
			obj.save()
			return redirect(gifts_list_detail_view, pk=gifts_list.pk)
	else:
		form = GiftForm()

	template = 'gifts/gift_form.html'
	context = {
		'form': form,
		'gifts_list': gifts_list,
	}
	return render(request, template, context)

def gift_detail_view(request, gift_pk):
	obj = get_object_or_404(Gift, pk=gift_pk)

	template = 'gifts/gift_detail.html'
	context = {'object': obj}
	return render(request, template, context)

@login_required
def gift_update_view(request, gift_pk):
	obj = get_object_or_404(Gift, pk=gift_pk)

	obj.can_user_edit(request.user)

	form = GiftForm(request.POST or None, instance=obj)
	if form.is_valid():
		form.save()
		return redirect(gift_detail_view, gift_pk=obj.pk)

	template = 'gifts/gift_form.html',
	context = { 'form': form, 'object': obj}
	return render(request, template, context)

@login_required
def gift_delete_view(request, gift_pk):
	obj = get_object_or_404(Gift, pk=gift_pk)
	gifts_list = obj.gifts_list
	if request.method == 'POST':
		obj.delete()
		return redirect(gifts_list_detail_view, pk=gifts_list.pk)

	template = 'gifts/gift_delete_confirm.html'
	context = {
		'object': obj,
		'gifts_list': gifts_list,
	}
	return render(request, template, context)

pages/views.py
from django.shortcuts import render, redirect

def landing_page(request):

    if request.user.is_authenticated:
        return redirect('user_home_page_view')

    template = 'pages/landing_page.html'
    context = {}
    return render(request, template, context)

users/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from gifts.models import GiftsList

def register_user_view(request):

    # redirect already authenticated user
    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            GiftsList.create_default_gifts_list(user)
            return redirect('login')
    else:
        form = UserCreationForm()

    template = 'registration/register.html'
    context = {'form': form}
    return render(request, template, context)

@login_required
def home_page_view(request):
    user_lists = GiftsList.objects.filter(owner=request.user)

    template = 'users/home_page.html'
    context= {'user_lists': user_lists}
    return render(request, template, context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous">
    <title>prostalista.pl {% block title %}{% endblock %}</title>
  </head>

  <body>
    <div class="container-fluid">
        {% include "navbar.html" %}
        <div class="row">
            <div class="col-10 mx-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>


  </body>
</html>

templates/gifts/base.html
{% load static %}

<!doctype html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">

    <title>Wishlist {% block title %}{% endblock %}</title>
  </head>

  <body>
    <body>
    <div class="container my-auto">
        <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card my-5">
            <div class="card-body">
                {% block content %}{% endblock %}
            </div>
            </div>
        </div>
        </div>
    </div>
</body>
  </body>
</html>

templates/gifts/gift_delete_confirm.html
{% extends 'gifts/gifts_base.html' %}

{% block gift_content %}
	{% load crispy_forms_tags %}
    <style>
        .asteriskField {display: none;}
    </style>

    <h1> Czy na pewno chcesz usunąć prezent: {{ object.name }}? </h1>
    <form action="{% url 'gift_delete_view' object.pk %}" method="post">

        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Usuń</button>
        <a href="{% url 'gifts_list_detail_view' object.gifts_list.pk %}" class="btn btn-info">Anuluj</a>
    </form>
{% endblock %}

templates/gifts/gift_detail.html
{% extends 'gifts/gifts_base.html' %}
{% block gift_content %}

    <h1>{{object.name}}</h1>

    <a href="{% url 'gift_update_view' object.pk %}" class="btn btn-primary">Edytuj <i class="fas fa-edit"></i></a>
    <a href="{% url 'gift_delete_view' object.pk %}" class="btn btn-danger">Usuń <i class="fas fa-trash-alt"></i></a>
    <a href="{% url 'gifts_list_detail_view' object.gifts_list.pk %}" class="btn btn-outline-info">Powrót do listy <i class="fas fa-backward"></i></a>

{% endblock %}

templates/gifts/gift_form.html
{% extends 'gifts/gifts_base.html' %}

{% block gift_content %}
	{% load crispy_forms_tags %}
    <style>
        .asteriskField {display: none;}
    </style>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Zapisz</button>

        {% if object %}
            <a href="{% url 'gifts_list_detail_view' object.gifts_list.pk %}" class="btn btn-info">Anuluj</a>
        {% elif gifts_list %}
            <a href="{% url 'gifts_list_detail_view' gifts_list.pk %}" class="btn btn-info">Anuluj</a>
        {%endif%}

    </form>
{% endblock %}

templates/gifts/gifts_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            {% block gift_content%}{% endblock %}
        </div>
    </div>
{% endblock %}

templates/gifts/gifts_list_create.html
{% extends 'gifts/gifts_base.html' %}

{% block gift_content %}
	{% load crispy_forms_tags %}
    <style>
        .asteriskField {display: none;}
    </style>

    <form action="/gifts_list_create" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Stwórz</button>
    </form>
{% endblock %}

templates/gifts/gifts_list_detail_view.html
{% extends 'gifts/gifts_base.html' %}



{% block gift_content %}

    <h1>{{object.name}}</h1>

    <a href="{% url 'gift_create_view' object.pk %}"type="button" class="btn btn-success">Dodaj prezent <i class="fas fa-plus"></i></a>
    <a href="#" type="button" class="btn btn-danger">Usuń listę <i class="fas fa-trash-alt"></i></a>

    <h2>Prezenty:</h2>

    {% for gift in object.gift_set.all %}
    <div class="row">
        <div class="col-6 card">
            <div class="card-body">
                <h5 class="card-title">{{ gift.name }}</h5>
                <p class="card-text"></p>
                <a href="{% url 'gift_detail_view' gift.pk %}" class="btn btn-info">Szczegóły <i class="fas fa-info"></i></a>
                <a href="{% url 'gift_update_view' gift.pk %}" class="btn btn-primary">Edytuj <i class="fas fa-edit"></i></a>
                <a href="{% url 'gift_delete_view' gift.pk %}" class="btn btn-danger">Usuń <i class="fas fa-trash-alt"></i></a>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

templates/gifts/landing_page_base.html
{% load static %}

<!doctype html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">

    <title>Wishlist {% block title %}{% endblock %}</title>
  </head>

  <body>
    <body>
    <div class="container my-auto">
        <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card my-5">
            <div class="card-body">
                {% block content %}{% endblock %}
            </div>
            </div>
        </div>
        </div>
    </div>
</body>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'landing_page' %}"><i class="fas fa-gift"></i></a
  <div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'landing_page' %}"></a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li><a class="nav-item nav-link active">{{ user.username }}</a></li>
        <li><a class="nav-item nav-link" href="{% url 'logout' %}">Wyloguj</a></li>
      {% else %}
        <li><a class="nav-item nav-link" href="{% url 'login' %}">Zaloguj</a></li>
        <li><a class="nav-item nav-link" href="{% url 'register' %}">Rejestruj</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/pages/landing_page.html
{% load static %}

<!doctype html>
<html lang="pl">
  
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">

    <title>prostalista.pl</title>
  </head>

  <body styles="height: 100%">
    <div class="container">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="jumbotron">
                <h1 class="display-4">Prosta Lista</h1>
                <p class="lead">Stwórz prostą i przejrzystą listę prezentów, którą szybko i łatwo udostępnisz swoim znajomym.</p>
                <hr class="my-4">
                <a href="{% url 'register' %}" class="btn btn-outline-success">Zarejestruj się</a>
                <a href="{% url 'login'%}" class="btn btn-success">Zaloguj</a>
            </div>
        </div>
    </div>

  </body>
</html>

templates/users/home_page.html
{% extends 'base.html' %}

{% block content %}
    <h3>Witaj {{ user.username }} </h3>


    <h4>Twoje listy prezentów:</h4>
    <ul>
        {% for gifts_list in user_lists %}
            <li><a href="{% url 'gifts_list_detail_view' pk=gifts_list.pk %}">{{ gifts_list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}